### ISSUE TITLE
Multiple Facebook Pages

### ISSUE THREAD

**Issue by stanwarri** [jonasva/laravel-facebook-insights#1]
Hello,

Great work on this package. I'm just wondering if its possible to make this package work with multiple Facebook pages. So I can dynamically insert the Facebook page ID into each function call.

Thanks

**Comment by jonasva** [comment]
Hi @stanwarri, 

Good suggestion, I've just added a `switchPage` method to the package for that. See here: https://github.com/jonasva/laravel-facebook-insights#switching-to-another-page

You'd need a different permanent access token for each page though, keep that mind.

**Comment by stanwarri** [comment]
Nice one @jonasva
Is it still required to set a default page property in the config file?

**Comment by jonasva** [comment]
No, you can leave it blank if you want. But you'd have to call the  `switchPage` method before doing any open graph queries of course.
