### ISSUE TITLE
Not working for Facebook SDK 5

### ISSUE THREAD

**Issue by EmilMoe** [jonasva/laravel-facebook-insights#2]
It seems that I cannot install your package, because it rely on Facebook SDK v4, but the newest is v5.

Do you have any plans to update this?

**Comment by jonasva** [comment]
Normally you should be able to install it as the dependency of laravel-facebook-insights is on Facebook SDK 4.0.*. Perhaps you have the 5.x-dev Facebook SDK already required somewhere in your project? (which would cause a conflict)
