### ISSUE TITLE
Returning empty Arrays or 0

### ISSUE THREAD

**Issue by richzertuche** [jonasva/laravel-facebook-insights#6]
Hi, I know it has been a while, but I was wondering if this is still working.

`FacebookInsights::getPagePosts($startDate, $endDate, $limit = 20);`

Is working fine, bringing all the posts but every other method returns either an empty array or a 0 like:

`FacebookInsights::getPageTotalPositiveFeedback($startDate, $endDate);`

Any help would really be appreciated, 

Thanks!

**Comment by richzertuche** [comment]
Cache was not showing the fresh info.

**Comment by mamulasa** [comment]
@richzertuche richzertuche: I have similar issues. What was your solution ? Set the 'cache-lifetime' => 0 ?

**Comment by richzertuche** [comment]
@mamulasa yes.

    'cache-lifetime' => 0,

Worked for me, but also makes loading time to be longer an use a FB request everytime.

**Comment by jonasva** [comment]
I'll look into the caching issue + update the API version in a couple of days when I find a bit of time.

**Comment by mamulasa** [comment]
@jonasva : Jonas, that would be great. I spent hours on this, with no success
