### ISSUE TITLE
Is it possible to dynamically change the facebook id?

### ISSUE THREAD

**Issue by xron89** [jonasva/laravel-facebook-insights#7]
I have multiple Facebook pages/accounts that I need to view the insights for, is it possible to change the id tokens dynamically e.g. stored in a database?

**Comment by jonasva** [comment]
There is a method available for switching pages, described [here](https://github.com/jonasva/laravel-facebook-insights/issues/1). The access tokens and ID storage isn't handled though, you'd have to put those in a config file or database by yourself.
